//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int B_Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> A_Date { get; set; }
        public Nullable<System.DateTime> D_Date { get; set; }
        public string Any_Question { get; set; }
        public int r_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
