//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Rooms = new HashSet<Room>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string H_Name { get; set; }
        public Nullable<int> R_Id { get; set; }
        public string H_Image { get; set; }
        public Nullable<rating> rating { get; set; }
        public string Performance { get; set; }
        public string H_Description { get; set; }
        public string H_Location { get; set; }
        public string H_Video { get; set; }
        public Nullable<byte> R_Rating { get; set; }
        public string H_Image2 { get; set; }
        public string H_Image3 { get; set; }
        public string H_Image4 { get; set; }
        public string H_Image5 { get; set; }
        public string H_Description2 { get; set; }
        public string H_Description1 { get; set; }
        public string H_Description3 { get; set; }
        public string H_Description4 { get; set; }
        public string H_Description5 { get; set; }
        public string H_Description6 { get; set; }
    
        public virtual Rate Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
