//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourism.Models
{
    using System;
    
    public enum ratingLevel : byte
    {
        Bab = 1,
        Fail = 2,
        Good = 3,
        Excellent = 4,
        Awesome = 5
    }
}
