//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int r_Id { get; set; }
        public string R_Name { get; set; }
        public string R_Description { get; set; }
        public string R_Image1 { get; set; }
        public string R_Image2 { get; set; }
        public string R_Image3 { get; set; }
        public string R_Image4 { get; set; }
        public string R_Image5 { get; set; }
        public string R_Image6 { get; set; }
        public int Id { get; set; }
        public string Number_Of_Beds { get; set; }
        public string R_Breadth { get; set; }
        public string R_Price { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> A_Date { get; set; }
        public Nullable<System.DateTime> D_Date { get; set; }
        public string Any_Question { get; set; }
        public string Any_Question_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
